# physical keys
LEFT_PINKY_UP = 1
LEFT_PINKY_DOWN = 2
LEFT_RING_UP = 3
LEFT_RING_DOWN = 4
LEFT_MIDDLE_UP = 5
LEFT_MIDDLE_DOWN = 6
LEFT_INDEX_UP = 7
LEFT_INDEX_DOWN = 8
LEFT_INDEX_RIGHT =  9
LEFT_THUMB_UP = 10
LEFT_THUMB_DOWN = 11

RIGHT_THUMB_UP = 12
RIGHT_THUMB_DOWN = 13
RIGHT_INDEX_LEFT = 14
RIGHT_INDEX_UP = 15
RIGHT_INDEX_DOWN = 16
RIGHT_MIDDLE_UP = 17
RIGHT_MIDDLE_DOWN = 18
RIGHT_RING_UP = 19
RIGHT_RING_DOWN = 20
RIGHT_PINKY_UP = 21
RIGHT_PINKY_DOWN = 22

# virtual keys
NO_KEY = 0
LPU, LRU, LMU, LI1U, LI2U, LTU,   RTU, RI2U, RI1U, RMU, RRU, RPU = range(1, 13)
LPM, LRM, LMM, LI1M, LI2M, LTM,   RTM, RI2M, RI1M, RMM, RRM, RPM = range(13, 25)
LPD, LRD, LMD, LI1D, LI2D, LTD,   RTD, RI2D, RI1D, RMD, RRD, RPD = range(25, 37)

VKEY_NAMES = {
    LPU: 'LPU',
    LPM: 'LPM',
    LPD: 'LPD',

    LRU: 'LRU',
    LRM: 'LRM',
    LRD: 'LRD',

    LMU: 'LMU',
    LMM: 'LMM',
    LMD: 'LMD',

    LI1U: 'LI1U',
    LI1M: 'LI1M',
    LI1D: 'LI1D',

    LI2U: 'LI2U',
    LI2M: 'LI2M',
    LI2D: 'LI2D',

    LTU: 'LTU',
    LTM: 'LTM',
    LTD: 'LTD',

    RTU: 'RTU',
    RTM: 'RTM',
    RTD: 'RTD',

    RI2U: 'RI2U',
    RI2M: 'RI2M',
    RI2D: 'RI2D',

    RI1U: 'RI1U',
    RI1M: 'RI1M',
    RI1D: 'RI1D',

    RMU: 'RMU',
    RMM: 'RMM',
    RMD: 'RMD',

    RRU: 'RRU',
    RRM: 'RRM',
    RRD: 'RRD',

    RPU: 'RPU',
    RPM: 'RPM',
    RPD: 'RPD',
}

# virtual groups
LP = 1
LR = 2
LM = 3
LI = 4
LT = 5
RT = 6
RI = 7
RM = 8
RR = 9
RP = 10
